name: wheels

on:
  push:
    tags:
      - '**'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-latest, windows-2019]

    steps:
      # Check out repository using git-lfs
      - uses: actions/checkout@v4
        with:
          lfs: true

      # Python used to run cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install cibuildwheel
        run: python -m pip install --upgrade pip wheel setuptools packaging cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # Options (https://cibuildwheel.readthedocs.io/en/stable/options/)
        env:
          CIBW_SKIP: cp36-* cp37-* cp38-* *pp37-* pp38-* *musllinux* *win_amd64* *win_arm64* *win32*
          CIBW_BEFORE_BUILD_MACOS: python3 -m pip install --upgrade pip wheel setuptools cffi packaging
          # CIBW_BEFORE_BUILD_WINDOWS: python3 -m pip install --upgrade pip wheel setuptools cffi packaging
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          # CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_BUILD_FRONTEND: "build"
          # CIBW_PROJECT_REQUIRES_PYTHON: ">=3.9"

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
